### ISSUE TITLE
Are you still sure about you command?

### ISSUE THREAD

**Issue by changemenemo** [jazzdd86/vboxwebsrv#1]
ssh -L 0.0.0.0:18083:localhost:$PORT $1 "killall vboxwebsrv; vboxwebsrv -p $PORT -A null"

Me it gets could not resolve the hostname. I ve tried every ip address, I m not using 22 as ssh port also

**Comment by jazzdd86** [comment]
It works fine for me, I just deleted my websrv container to try it out.
I have never tried using another ssh port. Maybe that is the issue here. Did you test it with the standard ssh port?

**Comment by changemenemo** [comment]
sadly I can't test with the ssh service port, it s produciton machien so I can't stop everything for that. Its certainly the issue yes, what would be the run command with another sshport?

**Comment by jazzdd86** [comment]
ok, it was just a minor change, but I added the possibilty to configure the ssh port. See last line in the README for information.

**Comment by changemenemo** [comment]
okey I will try it in a moment

**Comment by changemenemo** [comment]
with the new changes I have: 
ssh: connect to host 192.168.2.129 port 22: Operation timed out

**Comment by jazzdd86** [comment]
did you pull the latest image from docker hub? did you use -e SSH_PORT=portNumber environment variable?

**Comment by changemenemo** [comment]
yes sure at 100%

**Comment by jazzdd86** [comment]
```
$ docker run -it --name=vbox_websrv_1 -e SSH_PORT=50345 jazzdd/vboxwebsrv test@192.168.1.1
ssh: connect to host 192.168.1.1 port 50345: Connection refused
```

This is my command I used for testing. It tries to connect to port 50345, which is not used for anything  - so connection refused is ok. But the import part is, it tries to connect on the given port and not at the default port as for you.
Could you give me your docker command, the docker inspect output and the console output at container creation?
you could also start the container and try out the run.sh script manually, by connecting a bash to the container. maybe we will get closer to the issue you have

**Comment by changemenemo** [comment]
yes seems to work with the password version. I have maybe done something wrong. I will test further anyway. thanks for your help :)
