### ISSUE TITLE
"Host key verification failed" error

### ISSUE THREAD

**Issue by mountaindude** [jazzdd86/vboxwebsrv#4]
Can't wrap my head around this... Prob something trivial that I am missing.

I get the new key pair, and copy it to the remote server (where virtualbox is installed).
I have tried the key by doing a "ssh -i ssh/id_rsa my-user-name@<ip of remote server>. Works fine. 

But when doing a docker-compose up I get 

```
$ docker-compose up
Recreating vbox_websrv_1 ... done
Recreating vbox_http     ... done
Attaching to vbox_websrv_1, vbox_http
vbox_websrv_1  | Host key verification failed.
vbox_http      | Using following global configuration parameters:
vbox_websrv_1  | Host key verification failed.
vbox_http      | Array
vbox_http      | (
vbox_http      |     [browserRestrictFolders] => Array
vbox_http      |         (
vbox_http      |             [0] => /home
vbox_http      |             [1] => /usr/lib/virtualbox
vbox_http      |             [2] =>
vbox_http      |         )
vbox_http      |
vbox_http      |     [noAuth] => true
vbox_http      | )
vbox_http      |
vbox_http      |
vbox_http      | Using the following linked server instances:
vbox_http      | Array
vbox_http      | (
vbox_http      |     [0] => Array
vbox_http      |         (
vbox_http      |             [name] => Pro3
vbox_http      |             [username] => admin
vbox_http      |             [password] => admin
vbox_http      |             [location] => http://vbox_websrv_1:18083/
vbox_http      |         )
vbox_http      |
vbox_http      | )
vbox_http      | 2019/04/27 23:06:59 [notice] 1#1: using the "epoll" event method
vbox_http      | 2019/04/27 23:06:59 [notice] 1#1: nginx/1.14.2
vbox_http      | 2019/04/27 23:06:59 [notice] 1#1: OS: Linux 4.9.125-linuxkit
vbox_http      | 2019/04/27 23:06:59 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
vbox_http      | 2019/04/27 23:06:59 [notice] 1#1: start worker processes
vbox_http      | 2019/04/27 23:06:59 [notice] 1#1: start worker process 11
vbox_http      | 2019/04/27 23:06:59 [notice] 1#1: start worker process 12
vbox_http      | 2019/04/27 23:06:59 [notice] 1#1: start worker process 13
vbox_http      | 2019/04/27 23:06:59 [notice] 1#1: start worker process 14
vbox_websrv_1 exited with code 255
vbox_websrv_1  | Host key verification failed.
```

Any ideas?
Is there a debug mode I could turn on for the vbox_websrv_1 container?

**Comment by mountaindude** [comment]
Found it. 

When running the container via a docker-compose.yml, you don't get the interactivity needed to accept the fingerprint. 

Running things via docker run... works.

**Comment by bufanda** [comment]
You should bind-mount a known_hosts file to your container. Could be your users, so you won't need an interactivity and the known_host doesn't get lost if you rebuild your container.

**Comment by romprod** [comment]
> You should bind-mount a known_hosts file to your container. Could be your users, so you won't need an interactivity and the known_host doesn't get lost if you rebuild your container.

I have the same problem here, I've also tried bind-mounting a known_hosts file as suggested above but that still doesn't work unless I make the container interactive and manually login.

**Comment by jazzdd86** [comment]
Thats how my compose file looks, where I start the vboxwebsrv. I am mounting the complete .ssh folder into the container, so key files and known_host are available for the container.

```

 vbox_websrv:
        container_name: vbox_websrv
        restart: always
        volumes:
            - "./ssh:/root/.ssh"
        environment:
            USE_KEY: 1
        image: jazzdd/vboxwebsrv
        command: user@server

```
